### ISSUE TITLE
Přendat návrh GUI z papíru do PC (mock up design aplikace)

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#10]
-> např. https://gomockingbird.com/

**Comment by hlavja** [comment]
Krásné skoro ráno :)

https://gomockingbird.com/projects/kp1gc76

Veřejná část? Připomínky....

**Comment by LuTauch** [comment]
Chválím za dodání všech stránek, jako návrh je to dostačující, v tom programu toho o moc víc udělat nejde, je to jen pro představu. V reálu to bude muset vypadat o dost lépe, pohrát si s těmi styly, rozložením, písmem, elementy atd... Co se týče té implementace vybírání času v registraci tutorů, našla jsem, že v bootstrapu existují nejen datepickery, ale i timepickery, takže pokud to půjde, můžeme použít hotovou komponentu. 
(př. https://jdewit.github.io/bootstrap-timepicker/ )

Tento úkol uzavírám, ale zároveň Ti Kubo vytvářím další a to vytvořit ještě responzivní verze stránek. 
Takže chceme stránky pro desktop, tablet i telefon. 
(To už nebude tak těžké, jen to tam nějak přeházíš nejspíš)

P.S. Filip k tomu designu měl nějaké připomínky, už jste to vyřešili?
