### ISSUE TITLE
Schůzka CIV - vyřešit Orion

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#24]

**Comment by hachaf** [comment]
Schůze s p. Jindrou (CIV) proběhla. Pan Jindra dodá proxy, která zajistí přesměrování příchozích nepřihlášených uživatelů a v případě přihlášení přesměruje uživatele na Shibboleth, kde se ověří jejich totožnost a na námi vystavené API odešle login, email, jméno, příjmení a uživatele přesměruje zpět na SSCIS.

Pro testovací účely během výstavby proxy je potřeba nastavit API tak, aby po zpracování requestu vypsala hodnoty proměnných, které obdrží.

**Comment by LuTauch** [comment]
Výborně, Filipe. Uzavírám issue. :-)
