### ISSUE TITLE
Chybějící uživatelský profil

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#41]
Chybí uživatelský profil, který by měl být vidět po přihlášení?

**Comment by hlavja** [comment]
Uživatelský profil mám připravený - http://prntscr.com/j8lrd6, musím se domluvit s Filipem a nastrkat to tam v usecasech

**Comment by hachaf** [comment]
Přidat rozvrh.

**Comment by hlavja** [comment]
#35
