### ISSUE TITLE
Opravit zarovnání

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#45]
Opravit zarovnání select boxů ve foruláři Žádosti o tutorství

![image](https://user-images.githubusercontent.com/33037053/39064646-7fbf9492-44cf-11e8-96a2-12b7ed1bcc41.png)

A možná by mohli být i kratší ty políčka..

**Comment by hlavja** [comment]
Done - http://prntscr.com/j8ln5s
