### ISSUE TITLE
Odsazení obsahu stránek při zmenšení okna

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#50]
Při zmenšení okna je obsah stránek přilepený k okraji -> globálně zvětšit odsazení obsahu (nejlépe z obou stran, hlavně zleva).
tj. Všude používáš třídu container-fluid - nastav jí v css nějaký padding alespoň těch 15 px, což tam bývá defaultně.
 
![image](https://user-images.githubusercontent.com/33037053/39428764-d9ada9ba-4c88-11e8-814c-bd8071b55519.png)

Pozn.: Pohraj si s těm třídami a hlavně s hierarchií tříd. Místy nedodržuješ konvenci (to, co jsem ti říkala na začátku - container - row - column) -> pak se ti to zbytečně celý rozhodí ;-). 
https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by hlavja** [comment]
Odsazení se opravilo při opravě horizontálního scrollování

http://prntscr.com/jbywg9
