### ISSUE TITLE
Úprava menu

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#51]
1) Zvětšit písmo u záložek menu při zmenšení okna.

![image](https://user-images.githubusercontent.com/33037053/39430189-75ccee9c-4c8d-11e8-95b4-5f06a10e4985.png)

2) Zvětšit logo Zču - > při normální i zmenšené velikosti okna (třída .nav-brand, nemusíš k tomu používat svoji třídu .navbar-logo)
https://mdbootstrap.com/components/navbar/ - část Supported content
https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by hlavja** [comment]
1. Když se přihlásí admin tak se to tam vejde jen tak tak vz. http://prntscr.com/jbyzh2 , nevím zda jde nastavit různou velikost písma podle role která je přihlášená.

2. Logo jsem zvětšil a smazal .navbar-logo díky ;-)

**Comment by LuTauch** [comment]
Ad1) asi to klidně nastav různě. Nebo to aspoň vyzkoušej. 
Btw. je tam překlep - žádosti tutotů -> žádosti tutorů
Ad2) super :-)

**Comment by hachaf** [comment]
Odebrat položky menu pro Admina.
