### ISSUE TITLE
Min šířka body

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#52]
Nastav nějakou minimální šířku obrazovky, aby se nedala zmenšit na úplné minimum a celé se to nerozjelo. 
-> po nastavení uprav zobrazení, aby vše sedělo. 
Na obr. níže vidíš, že je to zle. (ten napsis zasahuje do menu, ...)

![image](https://user-images.githubusercontent.com/33037053/39431589-835decb0-4c91-11e8-9ac4-4a8c0e481860.png)

**Comment by LuTauch** [comment]
Dobře, v tém staré verzi to nejspíš ještě šlo.

**Comment by hlavja** [comment]
Ono v tom vývojovém prostředí to jde zmenšit i teď mně po opravě, ale okno chromu nedokážu víc zmenšit.
