### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#53]
Posuň footer až dolů (zkus to nějak).

![image](https://user-images.githubusercontent.com/33037053/39432214-2736ff56-4c93-11e8-88d7-76ba9829d20d.png)

Občas se footer nezobrazí z rohu do rohu: (viz pravá strana)
![image](https://user-images.githubusercontent.com/33037053/39432172-13c5ba70-4c93-11e8-8956-df6de5682ad6.png)

**Comment by hlavja** [comment]
Ad1. jako nebudu lhát sežral jsem u toho celou jednu tabulku čokolády ale problem solved HALELUJAA (a ano řešení bylo docela triviální)  http://prntscr.com/jbzx5h

Ad2. pořád problém s verzí kde není opravené horizontální scrollování ;-)

**Comment by LuTauch** [comment]
super :-)
