### ISSUE TITLE
Zobrazení uživ. jména po přihlášení

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#55]
Přidat někam do menu uživatelské jméno, pod kterým je uživatel přihlášen. 
Pod Logout nebo vedle :-)

**Comment by hlavja** [comment]
Už připraveno jenom mi nějak najde napsat controller to aby to zobrazovalo nick takže tam mám na pevno zatím USERNAME.

http://prntscr.com/jc009t

**Comment by LuTauch** [comment]
Super :-)
