### ISSUE TITLE
Horizontální scrollbar

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#59]
Po přihlášení uživatele na stránce "Vypsat lekci" objevuje horizontální scrollbar.

![image](https://user-images.githubusercontent.com/33037053/39653772-97f9d6c0-4ff2-11e8-82c5-f0b63b1cb5ed.png)

-> bylo by hezké ten formulář trošku zmenšit (tím by se to nejspíš i vyřešilo)

**Comment by LuTauch** [comment]
Souvisí to s nasazením nových pohledů (#57). Se zbytkem počkám :-)

**Comment by hlavja** [comment]
http://prntscr.com/je0nd5
