### ISSUE TITLE
Nová aktualita

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#60]
Po otevření aplikace se objeví tato zvláštní aktualita. Je to tak správně?  

![image](https://user-images.githubusercontent.com/33037053/39676573-5bb111c0-516d-11e8-89e5-77bd64a91830.png)

**Comment by LuTauch** [comment]
Tyto zvláštní hlášení se zobrazují i na stránce Novinky.

![image](https://user-images.githubusercontent.com/33037053/39676661-d572beae-516e-11e8-885d-7c9163438d8d.png)

**Comment by hachaf** [comment]
Ano, toto je v pořádku, je to jednoduše způsobeno tím, že v databází je uložená novinka (resp. několik novinek) s takovýmhle obsahem.
