### ISSUE TITLE
Nadbytečné <div>s

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#61]
Zrušit levý horní div, který nemá využití a působí rušivě (viz obr.). Ten pravý bych zrušila také. Zobrazila bych ho max. opravdu až po přihlášení uživatele.
![image](https://user-images.githubusercontent.com/33037053/39676614-0dc4a39a-516e-11e8-8697-4c42ea594605.png)

**Comment by hachaf** [comment]
Kuba - rozpracované

**Comment by hlavja** [comment]
#54

**Comment by hlavja** [comment]
Prošel jsem to a přepsal podmínky if v kódu, mělo by to bejt v pořádku
