### ISSUE TITLE
Překlepy

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#63]
Prosím, opravit překlep: -> na přihlaste
![image](https://user-images.githubusercontent.com/33037053/39676728-a51141bc-516f-11e8-9aee-d885aec605f2.png)

i tady: 
![image](https://user-images.githubusercontent.com/33037053/39676736-d8d32a7e-516f-11e8-9649-a591d6f9981f.png)

**Comment by hlavja** [comment]
První done, druhej překlep nevidím :)

**Comment by LuTauch** [comment]
Má tam být všude přihlaSte, ne přihlaŠte. 
Nebo tak je to alespoň spisovně. Přihlásit se -> přihlasste se :-)

**Comment by hlavja** [comment]
Já čeština více se učit muset.
