### ISSUE TITLE
Chyba v menu

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#64]
Dvakrát záložka potřebuji pomoct -> proto se to tam asi nevejde že? 

![image](https://user-images.githubusercontent.com/33037053/39676777-4abb805a-5170-11e8-8ab0-dd7e5d7ab799.png)

(Pokud by se to tam z nějakého důvodu nevešlo i po vymazání té jedné záložky, budeme to muset nějak vyřešit. Takto široké menu mít nemůžeme :-)

**Comment by hlavja** [comment]
Já jí tam už nemám

**Comment by LuTauch** [comment]
Ok, to je dobře. 
Ale tady u admina -> nemůže tam být takhle hrozně velká díra v menu. Zkus dát to přihlášení a admin do stejné řádky akorát se zarovnáním doprava jako je ta záložka Uživatelé. 
Takhle velké a široké menu nechat nemůžeme. To je menu přes půl stránky -> a když je fixní, tak tam je celou dobu.
![image](https://user-images.githubusercontent.com/33037053/39677119-20530b34-5176-11e8-9dc1-245d0e40015b.png)
