### ISSUE TITLE
Úprava menu po přihlášení?

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#65]
Co kdybychom z menu vyndali záložku Chci pomáhat v případě, že ten člověk už je tutor a už pomáhá? Pak tato záložka ztrácí smysl ne? 
To samé - předpokládáme, že tutor nepotřebuje pomoct..

**Comment by hlavja** [comment]
Tak jako i TUTOR může potřebovat pomoct z jiného předmětu? 🤔 
Jinak Chci pomáhat u TUTORA nevidím

**Comment by LuTauch** [comment]
tak SSC je primárně pro prváky...a tutoři by měli být ze 3.-5. ročníku (nebo alespoň tak se to píše v popisu, co tam uvádíme). 
a tady jsou dvě menu tutor i netutor a jsou tam stejné záložky. 
![image](https://user-images.githubusercontent.com/33037053/39677149-83782528-5176-11e8-9a9c-448329e3caf8.png)
A 
![image](https://user-images.githubusercontent.com/33037053/39677156-9e841c82-5176-11e8-8239-6441ca0e2e94.png)


tzn. To samé - pokud jde o uživatele, který není tutor, neměl by mít možnost si vypsat lekci jako tutor. 
-> a záleží, co znamená záložka Moje lekce - ta se dá asi přizpůsobit tutorovi i studentovi. 

To samé opět i pro Admina -> admin tam určitě nebude mít Chci pomáhat a Potřebuji pomoct. (Pokud nejde o to, že si tam ty záložky třeba může opravovat nějak). 

Každopádně to menu se musí přizpůsobit podle role. 

A ještě jedna věc k menu -> zkus prosím posunout záložku kontakt úplně nakonec (aby byla poslední - samozřejmě před jménem přihlášeného uživatele). Vetšinou to tak bývá.

**Comment by hachaf** [comment]
Kuba - řeší se
