### ISSUE TITLE
Nefunkční přidávání lekcí

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#66]
Když si jako tutor chci vypsat nějakou novou lekci a dám vytvořit událost, něco se stane (asi), ale objeví se prázdná stránka a po kliknutí na záložku Moje lekce se tato lekce také nezobrazí. 
![image](https://user-images.githubusercontent.com/33037053/39676868-ce987e2c-5171-11e8-8e20-ebfc8fd88e16.png)

**Comment by hlavja** [comment]
Mně funguje -> http://prntscr.com/jeiiq2

**Comment by LuTauch** [comment]
A poté, co dáš vytvořit událost se něco stane? Objeví se ti ta událost někde? Nebo aspoň nějaká hláška o tom , že událost byla vytvořená? 
(Tu by to mimochodem chtělo v každym případě)

**Comment by hachaf** [comment]
Opravit "Čas do".

**Comment by hachaf** [comment]
Opraveno, commitnuto, pushnuto.
