### ISSUE TITLE
Vyznačení aktuální záložky v menu

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#67]
Vyznačit v menu, na které záložce se zrovna nacházím.

![image](https://user-images.githubusercontent.com/33037053/39676880-fc637afa-5171-11e8-80de-19349fb938d3.png)

Takto na první pohled není poznat, na které stránce zrovna jsem.

**Comment by hlavja** [comment]
Sakra to fungovalo, se muselo něco posrat :D

**Comment by hlavja** [comment]
Okey  LUL
