### ISSUE TITLE
Rozvrh po přihlášení

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#69]
I po přihlášení se dole na stránce zobrazuje hláška "PRO ZOBRAZENÍ NEPRAVIDELNÉHO ROZVRHU SE PROSÍM PŘIHLAŠTĚ":

![image](https://user-images.githubusercontent.com/33037053/39677055-319a1352-5175-11e8-8c52-8e9397fc44ad.png)

**Comment by hlavja** [comment]
#40
