### ISSUE TITLE
2x tlačítko detail

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#81]
V seznamu lekcí u lekce vždy dvě tlačítka Detail, z čehož jen jedno funkční. 

![image](https://user-images.githubusercontent.com/33037053/39769761-61e5aeb2-52ed-11e8-81f2-118e1b6e4778.png)

To první vyhodí bad request:

![image](https://user-images.githubusercontent.com/33037053/39769784-6c2131da-52ed-11e8-9957-5ca109b42ba6.png)

**Comment by hachaf** [comment]
Opraveno, commitnuto.
