### ISSUE TITLE
Úprava a mazání novinek

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#83]
-> ~~nelze vytvořit novou novinku~~
->~~nelze upravit starou novinku (btw. stránka se jmenuje EDIT - @hlavja  - zaměnit za Upravit)~~
->~~nelze smazat starou novinku~~
 U těchto operací vždy nastane Error 
![image](https://user-images.githubusercontent.com/33037053/39786188-a49cea9a-531f-11e8-8e34-46fb0cd58c08.png)

**Comment by hachaf** [comment]
Opraveno, commitnuto.
