### ISSUE TITLE
Vypsání lekce

### ISSUE THREAD

**Issue by LuTauch** [Luckyboys2018/SSCIS#86]
Při vypsání lekce se požadavek odešle, ale na stránce Moje lekce se nezobrazí.
Tudíž se pravděpodobně nezobrazí ani adminovi v nabídce pro schválení. 

![image](https://user-images.githubusercontent.com/33037053/39769846-9f6425a2-52ed-11e8-9fa2-493ea74b386d.png)

**Comment by hachaf** [comment]
Opraveno, commitnuto.
