### ISSUE TITLE
TC.01.11.Zobrazení zpětných vazeb

### ISSUE THREAD

**Issue by hlavja** [Luckyboys2018/SSCIS#88]
Zadáno
Od 01.01.2018
Do 01.01.2080

Po kliknutí na Zobrazit se zobrazila chybová hláška Error.

**Comment by hachaf** [comment]
Na tohle jsem narazil už včera, makám na tom.

**Comment by hachaf** [comment]
Opraveno.

**Comment by hachaf** [comment]
Nasazeno.
